# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          cat requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          ls -la
      - name: Archive venv
        run: |
          tar czf venv.tar.gz .venv
      - name: Upload venv archive as artifact
        uses: actions/upload-artifact@v4
        with:
          name: venv
          path: venv.tar.gz
          if-no-files-found: error

  security-checks-sast:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Download venv artifact
        uses: actions/download-artifact@v4
        with:
          name: venv
          path: .
      - name: Extract venv
        run: |
          tar xzf venv.tar.gz
      - uses: snyk/actions/setup@master
      - name: Snyk monitor (dépendances)
        run: |
          source .venv/bin/activate
          snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Snyk Code (analyse du code source)
        run: |
          source .venv/bin/activate
          snyk code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: security-checks-sast
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Download venv artifact
        uses: actions/download-artifact@v4
        with:
          name: venv
          path: .
      - name: Extract venv
        run: |
          tar xzf venv.tar.gz
      - name: Lint with flake8
        run: |
          source .venv/bin/activate
          pip install flake8
          flake8 . --count --show-source --statistics
          flake8 . --count --exit-zero --statistics
      - name: Test with pytest
        env:
          DJANGO_SECRET_KEY: dummysecretkeyforci
        run: |
          source .venv/bin/activate
          pip install pytest pytest-django
          pytest tests/ --maxfail=2 --disable-warnings -v

  # Deploy to test environment

  # DAST (Dynamic Application Security Testing) with OWASP ZAP on a test environment
  # for DAST, we need a running instance of the api/web application to scan
  security-checks-dast:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: 'https://ualexon.com' # Replace with your test environment URL